### ISSUE TITLE
not finding all solutions

### ISSUE THREAD

**Issue by kurgandk** [PrettyFlower/Wordle5x5CSharp#1]
On my machine both the recursive and nonrecursive gives me 194 but it should be 537 (wo anagrams) or 831 (w anagrams?)

**Comment by PrettyFlower** [comment]
I checked this morning and I'm getting 538. What OS are you running on? Would you mind telling me what the count of WordIdxsToText is at the end of the Util.Load() function?

**Comment by kurgandk** [comment]
Win 11, vs22, running on a i9

**Comment by kurgandk** [comment]
I'll check the ret when I get home

**Comment by kurgandk** [comment]
WordIdxToText: 6877

**Comment by PrettyFlower** [comment]
Ok...I'm getting 5977. Would you mind sticking this code at the bottom of Util.Load() and pasting the output file up here so I can diff it against what I'm getting?
```C#
using(var streamWriter = new StreamWriter("WordIdxsToText.txt"))
{
    foreach(var word in WordIdxsToText)
    {
        streamWriter.WriteLine(word);
    }
}
```
Here's mine for reference.
[WordIdxsToText.txt](https://github.com/PrettyFlower/Wordle5x5CSharp/files/13274237/WordIdxsToText.txt)

**Comment by kurgandk** [comment]
[WordIdxsToText-6877.txt](https://github.com/PrettyFlower/Wordle5x5CSharp/files/13278772/WordIdxsToText-6877.txt)

**Comment by PrettyFlower** [comment]
Thanks for posting the file. It looks like it's parsing 6 character words instead of 5. I'm betting this has to due with the line endings being different in the input file. Try changing the LINE_LENGTH variable from 7 to 6 and let's see if that fixes it.

**Comment by kurgandk** [comment]
![image](https://github.com/PrettyFlower/Wordle5x5CSharp/assets/9090580/7ce98c1d-a811-40ad-8726-51530e105913)
Looks like that was it

**Comment by PrettyFlower** [comment]
Great! Thanks for your help here. I’ll have to mess around with this a bit before publishing a fix.
